### ISSUE TITLE
Support transfer of TAR files

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#111]

**Comment by helrond** [comment]
I am experiencing the following unexpected behavior: tar and tar.gz files are failing silently (I am not getting either an error or success email, and the files are not appearing in the UI). Looking at the cron log, it appears that the script is failing at some point after [line 75 of cron.py](https://github.com/RockefellerArchiveCenter/aurora/blob/master/project_electron/transfer_app/cron.py#L75) - I suspect the `BAGLog.log_it()` function is failing.

**Comment by catmurphy** [comment]
Looking like valid_bag.tar when untarred has a valid_bag folder and a ._valid_bag hidden file, which makes this invalid (unexpected and unplanned for, for sure).  Darnell found and Cathy confirmed;  will check out the other .tar and .tar.gz to see if they all have the little hidden file.

**Comment by helrond** [comment]
Thanks @catmurphy! I am sure the rest of them have this problem, since I created them all the same way. I will revisit my crappy TAR-making script...

**Comment by helrond** [comment]
After some research, determined this was another Mac OSX quirk: https://unix.stackexchange.com/questions/9665/create-tar-archive-of-a-directory-except-for-hidden-files
Have tested and this is performing as expected.
