### ISSUE TITLE
Maintain audit trail of transfer actions through event metadata

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#13]

**Comment by dboutmybizness** [comment]
@helrond can you clarify this item.. If what i think this is, is generating json of the transfer via an api endpoint? We wouldn 't need to keep an audit trail but as an enhancement use an api package to expose an endpoint.

**Comment by helrond** [comment]
@dboutmybizness This was intentionally written pretty vaguely. I think part of it is the enhanced error reporting we discussed last week (#108)  and then the second part of that is exposing that information, at least in the UI (#15) or via an API endpoint (#109). So I guess I would read this as a broad feature request that's probably more clearly specified in a number of other issues.

**Comment by helrond** [comment]
Closing this for now. We may want to specify an enhancement to this in the future, but I think the work done for #15 closes this issue as well.
