### ISSUE TITLE
Review Donor user groups and access to views

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#162]

**Comment by helrond** [comment]
Proposed user groups and permissions

## All Users
*  View all own organization transfers
*  View all own transfers
*  View dashboard for own organization
*  View rights statements for own organization
*  View BagIt Profile for own organization
*  View own organization profile
*  View own profile
*  Change own password

## RAC Users

### All RAC Users
*  View all transfers
*  View all organizations
*  View all organization profiles
*  View all rights statements
*  View all BagIt Profiles
*  View appraisal queue
*  View accessioning queue

### Appraisal Archivists
*  Accept or reject transfers
*  Add appraisal notes to transfers

### Accessioning Archivists 
*  Create accession records

### Managing Archivists
*  Accept or reject transfers
*  Add appraisal notes to transfers
*  Create accession records
*  Add/edit organizations
*  Add/edit users
*  Add/edit rights statements
*  Add/edit bag profiles

### System Administrator
*  Accept or reject transfers
*  Add appraisal notes to transfers
*  Create accession records
*  Add/edit organizations
*  Add/edit users
*  Add/edit rights statements
*  Add/edit bag profiles
*  Change system settings

**Comment by dboutmybizness** [comment]
Looks good, would need to start applying to see if their are any holes.  

So do we leave RACAdmin as a django superuser or do you see it more in line with utilizing groups?

**Comment by helrond** [comment]
I think RACAdmin should be the System Administrator. If it still makes sense to have a Django superuser for now that's cool, but I want to be careful about who has absolute power.
