### ISSUE TITLE
Fix upload time sorting in organization 'All Transfers' table 

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/aurora#191]
Sorting by the time column sorts ascending->descending day, but descending->ascending hour. E.g. if you order them by date newest to oldest they will display that way, but with the time of day being oldest to newest. Resulting sort is not strictly ordered by upload time.

**Comment by helrond** [comment]
This may be a useful blog post: https://datatables.net/blog/2014-12-18
