### ISSUE TITLE
Validate bag size

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#28]
Bag should be no larger than 2GB

**Comment by helrond** [comment]
Can someone from @RockefellerArchiveCenter/marist confirm/point to code that does this?

**Comment by dboutmybizness** [comment]
Actually If 2GB is the cap, I don't have to process the bag at all.. Will fail prior to processing and reflect in the app.

**Comment by helrond** [comment]
Yes, I agree that would be the desired approach!

**Comment by helrond** [comment]
Uploaded `large_bag` at 2017-10-18 11:30:51.073559 which should have failed because it is over 2GB, but instead it passed and the size reflected in the UI is wrong:

![screen shot 2017-10-18 at 12 26 01 pm](https://user-images.githubusercontent.com/607621/31730339-a32d383c-b3ff-11e7-8325-1cbb899e3af9.png)

**Comment by dboutmybizness** [comment]
code already merged to master, can be closed.
