### ISSUE TITLE
Open end dates not reflected in Rights Statements "view" page

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/aurora#310]
When an act has an end date expressed in years after the object's creation end date, it is reflect on the view page in a format such as "Applicable Date Rules   10 years after end date." However, when there is an "Open" end date for an act, "Applicable Date Rules" do not appear on the view page. To see whether the "Open" end date box is checked, I have to go to the "edit" page for the statement. I would like to see the "Open" end date reflected as an "Applicable Date Rule" on the view page.

**Comment by helrond** [comment]
This appears to be an issue not with open end dates but with statements that have a `start_date_period` of 0, not `end_date_period`, 'start_date` or 'end_date`. I have some questions about how accurate these statements are (at least based on what I'm seeing in our dev instance).
