### ISSUE TITLE
Add visual change to note button when note is added

### ISSUE THREAD

**Issue by EcZX** [RockefellerArchiveCenter/aurora#335]
# Is your feature request related to a problem? 
Under the appraisal queue, I did not notice the "add note" vs "edit note" button. 

# Describe the solution you'd like
A visual change like a different color or outline so that it stands out a little.

# Additional context
Please feel free to disagree but for me it was difficult to see.

**Comment by helrond** [comment]
@EcZX I implemented some code which changes the button color on the dev server. Can you take a look at let me know if this resolves the issue for you?

**Comment by EcZX** [comment]
@helrond Under the appraisal queue, I can see a clear distinction between the "add note" vs "edit note" button. Thanks for resolving the issue!
