### ISSUE TITLE
Edit UIs and notifications for consistent transfer tracking info and ids

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/aurora#337]
## Is your feature request related to a problem? Please describe.
Both donor and archivist users have difficulty searching for/locating a specific transfer in Aurora. Donor users have added their external identifier to the bag title name to aid searching, and archivists are currently tracking specific transfers by metadata including title, record type, creator, and upload time. Search/ locating specific transfers can be improved by adding transfer ids to tables and detail views consistently across the app and in email notifications.

### Transfer page table (both All Transfers and My Transfers tabs)
- Add external identifier to "Name" column in the format: `title (external identifier)`. If a bag is not valid, use the bag-it-name value instead.
- Add "Transfer File ID" column containing machine file id. 
- Reformat "Dates "column to remove day: month year - month year to make more room in the table
- Change column order to: Name, Transfer File ID, Status, Dates, ...
- Rename "Upload Time" column to "Transfer Date" to match Appraisal Queue

### Appraisal Queue
- Rename "Transfer File Name" column to "Transfer File ID" to match new column in Transfer page table. Table values should be the machine file id.

### Organization Page (Recent Transfers table)
- Rename column "Bag Name" to "Name" to match Transfer page table
- Change value in name column to match Transfer page table: `bag title (external identifier)`. If bag is not valid, use the bag-it-name value instead.
- Change "Upload Time" column name to be "Transfer Date" to match Transfer page table and Appraisal Queue table.

### Accession Record (Transfers table)
- Rename "Name" column to be "Transfer File ID" to match other tables in Aurora. Table values should be the machine file id.

### Transfer Details page
- Add the words "Details for" to the h1 ahead of the bag name to match the Appraisal Queue details modal.
- Add the machine file id as a `<p>` below the header if that value is available

![details view screenshot](https://user-images.githubusercontent.com/15254041/62137273-ac3bc880-b2b3-11e9-8878-97bffbe06e52.png)

### Appraisal Details modal
- Change the modal to match the Transfer Details page, ie. use the bag-it-name as the title and add the machine file id below the title as seen in the screenshot in the previous section.

### Email notification
- For transfers that pass validation, include the bag title and external identifier in the email text: ```The transfer [bag title (external identifier)] with the bag name [bag-it-name] was received at {} and has passed all automated validation checks:',
                'You can view the current status of this transfer at {}'```
- For transfers that fail validation, add additional text:  ```An error occurred for the transfer with bag name {}```

### Dashboard
- Leave the Recent Transfers section links as the bag-it-name, since these are just quick links that do not need to be complicated with additional identifiers.

## Describe alternatives you've considered
- We could use the transfer file id as the header in detail pages and on the Dashboard, but because invalid bags will not have this value, I'm suggesting sticking with the bag-it-name for consistency.
- There may be more explanatory text that could be added to the email notification for a failed bag since that notification cannot provide any metadata to help clarify which bag is invalid.

## Additional context
Once changes are made, communicate to donor users that the external identifier does not need to be added as part of the title.

**Comment by helrond** [comment]
@HaSistrunk I have pushed up these changes to the dev server, so you can see them in action. As I was doing this, I made a couple of adjustments to your suggestions:
- Updated the `bag_or_failed_name()` model method to return the title in the format you suggested. I've then used that model method pretty much everywhere.
- I used this version of the name in the Appraisal table too, rather than the `machine_file_identifier`
- Instead of calling the `machine_file_identifier` column `File Transfer ID` I simply called it `Identifier`
- Instead of using `Transfer Date` I used `Transfer Time`, since that more accurately reflects the data in the field and may also help avoid semantic collision between that field and the dates of records in the transfer.

**Comment by HaSistrunk** [comment]
The "Identifier" column in the Appraisal Queue table should now be called "Name", I think.

**Comment by helrond** [comment]
Good catch - got it!
