### ISSUE TITLE
detailed accession page in Aurora

### ISSUE THREAD

**Issue by EcZX** [RockefellerArchiveCenter/aurora#351]
## Is your feature request related to a problem? 
We are having trouble tracking down which accession is completed by who since we have multiple people working on accessioning material in Aurora. 

## Describe the solution you'd like
Is it possible to add a more detailed accession page in Aurora that includes: the accession number, identifiers and a detailed status on the accessions?

**Comment by helrond** [comment]
Related to (and may supercede) #344 

After saving an accession, the user should be redirected to this accession detail page.

**Comment by helrond** [comment]
A slightly more specific list of fields:
- Accession number from ArchivesSpace (if it exists)
- ArchivesSpace identifier (ie `/repositories/2/accessions/12` if it exists
- Each transfer in the accession (ideally linked to that transfer's detail page) with the status of that transfer
- The overall status of the accession (in progress/complete) which can be calculated from the statuses of the transfers.
