### ISSUE TITLE
Display associated Accession Number in Aurora

### ISSUE THREAD

**Issue by EcZX** [RockefellerArchiveCenter/aurora#352]
## Is your feature request related to a problem?
We are having trouble tracking down which accession is completed by who since we have multiple people working on accessioning material in Aurora.

## Describe the solution you'd like
Is there a way to display the accession number associated in ArchivesSpace in Aurora?

**Comment by helrond** [comment]
If available, this should be displayed in the accession list view, as well as on the accession detail page, as per #351

**Comment by helrond** [comment]
fixed by aa001f92dac0e8e1dd5cd5b6ff5e3fb5239bf182
