### ISSUE TITLE
Add unit test coverage for `merge_rights`

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#384]
## Is your feature request related to a problem? Please describe.
The `merge_rights` method on the `RightsStatement` is very complex and does not have any unit test coverage. It would be awesome to refactor this to make it a bit more understandable but it's tough to even start when changes aren't testable.

## Describe the solution you'd like
Add a test which covers this function (and all its branching logic).

**Comment by dboutmybizness** [comment]
After reviewing my proposed test would be:

 - Check to verify object type of `statement_list` (required param)
 - If methods object methods exist OR returns type expected (ex. get_rights_info_object)
 - merge_dates, possibly test pre and post
 - recommend a test for get_date_keys
 - merged statements len == statement groups (keys of statements by type)

In addition I believe much of refactor can be done at the same time as writing the test.

**Comment by helrond** [comment]
This looks pretty comprehensive to me.

I think you're right that refactor and tests can happen together, so I was thinking of this and #385 as a package.
