### ISSUE TITLE
Limit organizations to only one BagIt Profile

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#399]
## Is your feature request related to a problem? Please describe.
The original implementation of Aurora allowed organizations to have multiple BagIt Profiles. However, we so far don't have a use case for multiple Profiles associated with a single organization. 

Having multiple BagIt Profiles associated with an organization also blocks us from doing some things which would improve validation, like dynamically fetching the BagIt Profile's URL from Aurora, rather than having to rely on hardcoded URLs.

## Describe the solution you'd like
Remove the ForeignKey relationship on BagItProfiles to Organizations, and add a ForeignKey relationship from Organizations to BagIt Profiles. 
In BagIt Profile validation, fetch the BagIt Profile by using Django's `reverse` utility.
Additional work will need to be done in Views, Templates and API Serializers to account for the above changes.

## Describe alternatives you've considered
We could leave this as-is; it's not necessarily hurting anyone, but it's kind of annoying.

**Comment by p-galligan** [comment]
Not sure I'm understanding what's being asked for here: `Remove the ForeignKey relationship on BagItProfiles to Organizations, and add a ForeignKey relationship from Organizations to BagIt Profiles`. 

The wording is a bit confusing to me.

**Comment by helrond** [comment]
Right now there is a ForeignKey field on BagItProfiles (applies_to_organization) which points to the Organization model. This means that one Organization can have many BagItProfiles associated with it. What I'm asking for is to flip the relationship, and add a ForeignKey field on Organization that points to BagItProfiles.

**Comment by p-galligan** [comment]
@helrond I'm trying to think through the work for this one. I can remove `applies_to_organization` from the BagItProfile, and add something along the lines of `applies_to_profile` to the Organization model. 

Then I'd have to update every reference to `applies_to_organization` in the code, correct? There are a lot of references to the `applies_to_organization` field in a few different files. And I'd like to make this change with as little impact as possible.

**Comment by helrond** [comment]
I would suggest you call the field on Organization `bagit_profile` or something like that to make more semantic sense.

Starting by looking for those `applies_to_organization` fields is a good idea, but there will likely be other pieces of code affected by this change.
