### ISSUE TITLE
Debug updating of dashboard month and record type data on archive creation/deletion

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#405]
## Is your feature request related to a problem? Please describe.
Monthly counts of transfers and RecordType objects are created as bags are submitted to Aurora. The frequency of each month and type is then recorded and displayed on the Aurora dashboard. However, when transfers are deleted (as in dev, when cleanup happens) that frequency needs to be updated to accurately reflect data in the system.

## Describe the solution you'd like
Ensure that existing signals (in `aurora/bag_transfer/signals.py`) are working as expected. Suspect that the `pre_delete` signal for `Archives` should really be a `post_delete` signal.

**Comment by p-galligan** [comment]
Changing `Archives` to use `post_delete` works for the side dashboard data, but unfortunately causes and mismatch between the side panel dashboard and the bottom panel. Investigating, but see screenshot.

<img width="1196" alt="Screen Shot 2020-05-27 at 10 18 02 AM" src="https://user-images.githubusercontent.com/2585069/83032092-677fdb80-a003-11ea-975d-9db33ad0ab3e.png">

Transfers were deleted through the Django admin.

**Comment by p-galligan** [comment]
Know what would be smart? If I actually made the changes...
