### ISSUE TITLE
Validate data types as defined in specification

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#43]
See https://github.com/RockefellerArchiveCenter/project_electron/blob/master/transfer/bagit-specification.md

Fields of particular concern:

- Date-Start (ISO 8601)
- Date-End (ISO 8601)
- Languages (ISO 639-2)
- Bagging-Date (ISO 8601)

**Comment by helrond** [comment]
Still needs to be done.

**Comment by dboutmybizness** [comment]
This can be closed.
