### ISSUE TITLE
Change name of default branch

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/aurora#435]
In alignments with efforts to reduce harmful and oppressive language in all aspects of the RAC's work, the default branch on this repository should be renamed from `master` to `base`. 

1. Move to a new default branch and push:
```
git branch -m master base
git push -u origin base
```

2. Change default branch in GitHub.
3. Update any CI integrations (Travis CI/GitHub Actions) which rely on this branch.

Local clones can update refs as follows:
```
$ git checkout master
$ git branch -m master base
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/base
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/base
```

**Comment by HaSistrunk** [comment]
Note: this includes `master` and `docs-master` branches.

**Comment by HaSistrunk** [comment]
@helrond does this have deployment considerations?

**Comment by helrond** [comment]
@HaSistrunk The code on the server is essentially just another remote, so the instructions at the bottom there for local clones would apply. 

We may need to look at the deployment docs too.

**Comment by HaSistrunk** [comment]
Changed docs-master to docs-base. Still need to change master to base and then merge PR #439
