### ISSUE TITLE
Unable to reset password

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/aurora#584]
## Describe the bug
On the `/login` page if I click "reset my password" and enter my email address on the` /reset-password` page, I get an error.

## To reproduce
1. Go to /login
2. Click on "reset my password"
3. Enter valid email address
4. On production, see 500 error
5. On development, see "permission denied" error

## Expected behavior
I would receive email to reset password

## Error message or screenshots
From development:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/15254041/200412083-b9ec4f43-668c-4141-8249-32134a71fa42.png">

**Comment by helrond** [comment]
Closing as this issue is resolved in dev.
