### ISSUE TITLE
Adjust cognito implementation to allow login via localhost

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/aurora#670]
## Describe the bug
When a user builds aurora locally and goes to localhost:8000 to access the UI, cognito won't allow signing in. This may not be something we solve in the Aurora code, but filing an issue here to track resolution either way.

## To reproduce
1. Run `docker-compose up`
2. Go to localhost:8000
3. See url redirect to cognito user pool

## Expected behavior
To allow for local development, the user should be able to sign in or in some way access the Aurora UI in the browser.

## Error message or screenshots
<img width="361" alt="image" src="https://github.com/RockefellerArchiveCenter/aurora/assets/15254041/ff47e778-d1bb-4811-9781-c31e92e28916">

## Impact on your work
Blocks UI development.

**Comment by helrond** [comment]
@HaSistrunk There's a [section of the README](https://github.com/RockefellerArchiveCenter/aurora?tab=readme-ov-file#authentication) that addresses this. Open to suggestions for additions/subtractions/reorganization. That README is pretty long and it might be good to rethink how it's broken up.

**Comment by HaSistrunk** [comment]
> @HaSistrunk There's a [section of the README](https://github.com/RockefellerArchiveCenter/aurora?tab=readme-ov-file#authentication) that addresses this. Open to suggestions for additions/subtractions/reorganization. That README is pretty long and it might be good to rethink how it's broken up.

Gotcha. The middleware configs mentioned in the README don't exactly map to what I'm seeing in `settings.py`. I can take a crack at making sure the README is easy to follow for this.
